workflows: invert external workloads setup
We are sometimes hitting the following failure when creating the GCP VM:
```
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/***/regions/us-west2/subnetworks/default' is not ready
```

From GCP documentation, this comes from simultaneous resource operations:
https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-vm-creation

Since the GKE cluster creation is asynchronous, I suspect it is
conflicting with the GCP VM creation. Reversing setup order.

Signed-off-by: Nicolas Busseneau <nicolas@isovalent.com>